// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TortasYaniAPI.Data;

#nullable disable

namespace TortasYaniAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260521204857_AddProducts")]
    partial class AddProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("TortasYaniAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Badge")
                        .HasColumnType("TEXT");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IngredientesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Precio")
                        .HasColumnType("REAL");

                    b.Property<double>("Rating")
                        .HasColumnType("REAL");

                    b.Property<int>("Resenas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TamaniosJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Badge = "Popular",
                            Categoria = "Tortas Especiales",
                            Descripcion = "Deliciosa torta de chocolate con capas de bizcocho húmedo y ganache.",
                            Imagen = "https://res.cloudinary.com/ddfzttgyr/image/upload/v1774234559/torta_de_chocolate_wv8mi7.png",
                            IngredientesJson = "[\"Chocolate\",\"Harina\",\"Huevos\",\"Mantequilla\",\"Azúcar\"]",
                            Nombre = "Torta de Chocolate",
                            Precio = 85.0,
                            Rating = 4.9000000000000004,
                            Resenas = 124,
                            Stock = 12,
                            TamaniosJson = "[\"S\",\"M\",\"L\"]"
                        },
                        new
                        {
                            Id = 2,
                            Badge = "Popular",
                            Categoria = "Cheesecake y Pyes",
                            Descripcion = "Refrescante cheesecake con coulis de maracuyá tropical.",
                            Imagen = "https://res.cloudinary.com/ddfzttgyr/image/upload/v1774234883/Cheesecake_de_Maracuy%C3%A1_knhn3w.png",
                            IngredientesJson = "[\"Maracuyá\",\"Queso crema\",\"Galletas\",\"Crema\",\"Azúcar\"]",
                            Nombre = "Cheesecake de Maracuyá",
                            Precio = 80.0,
                            Rating = 4.9000000000000004,
                            Resenas = 110,
                            Stock = 0,
                            TamaniosJson = "[\"S\",\"M\",\"L\"]"
                        },
                        new
                        {
                            Id = 3,
                            Badge = "Favorito",
                            Categoria = "Tortas",
                            Descripcion = "Esponjosa torta de zanahoria con frosting de queso crema y nueces.",
                            Imagen = "https://res.cloudinary.com/ddfzttgyr/image/upload/v1774234868/Torta_de_Zanahoriaa_ury5wh.png",
                            IngredientesJson = "[\"Zanahoria\",\"Harina\",\"Huevos\",\"Nueces\",\"Queso crema\"]",
                            Nombre = "Torta de Zanahoria",
                            Precio = 65.0,
                            Rating = 4.7000000000000002,
                            Resenas = 76,
                            Stock = 5,
                            TamaniosJson = "[\"S\",\"M\",\"L\"]"
                        },
                        new
                        {
                            Id = 4,
                            Badge = "",
                            Categoria = "Tortas",
                            Descripcion = "Clásica torta de vainilla con crema suave y decoración elegante.",
                            Imagen = "https://res.cloudinary.com/ddfzttgyr/image/upload/v1774234876/torta_de_vainilla_vgcfkf.png",
                            IngredientesJson = "[\"Vainilla\",\"Harina\",\"Huevos\",\"Mantequilla\",\"Leche\"]",
                            Nombre = "Torta de Vainilla",
                            Precio = 60.0,
                            Rating = 4.5999999999999996,
                            Resenas = 89,
                            Stock = 15,
                            TamaniosJson = "[\"S\",\"M\",\"L\"]"
                        },
                        new
                        {
                            Id = 5,
                            Badge = "Premium",
                            Categoria = "Matrimoniales",
                            Descripcion = "Elegante torta matrimonial de varios pisos decorada a medida.",
                            Imagen = "https://res.cloudinary.com/ddfzttgyr/image/upload/v1774234891/Torta_Matrimonial_qhxegx.png",
                            IngredientesJson = "[\"Vainilla\",\"Fondant\",\"Crema\",\"Flores\",\"Perlas\"]",
                            Nombre = "Torta Matrimonial",
                            Precio = 250.0,
                            Rating = 5.0,
                            Resenas = 45,
                            Stock = 2,
                            TamaniosJson = "[\"M\",\"L\",\"XL\"]"
                        },
                        new
                        {
                            Id = 6,
                            Badge = "Especial",
                            Categoria = "Quinceañeros",
                            Descripcion = "Torta especial para quinceañeras con decoración rosa y detalles dorados.",
                            Imagen = "https://res.cloudinary.com/ddfzttgyr/image/upload/v1774234897/Torta_de_Quincea%C3%B1era_evxzmp.png",
                            IngredientesJson = "[\"Vainilla\",\"Fondant rosa\",\"Crema\",\"Flores\",\"Brillantina\"]",
                            Nombre = "Torta de Quinceañera",
                            Precio = 200.0,
                            Rating = 4.7999999999999998,
                            Resenas = 62,
                            Stock = 3,
                            TamaniosJson = "[\"M\",\"L\",\"XL\"]"
                        },
                        new
                        {
                            Id = 7,
                            Badge = "",
                            Categoria = "Cheesecake y Pyes",
                            Descripcion = "Clásico pie de limón con merengue tostado y base crocante.",
                            Imagen = "https://res.cloudinary.com/ddfzttgyr/image/upload/v1774234905/Pie_de_Lim%C3%B3n_plhcyw.png",
                            IngredientesJson = "[\"Limón\",\"Huevos\",\"Azúcar\",\"Galletas\",\"Mantequilla\"]",
                            Nombre = "Pie de Limón",
                            Precio = 55.0,
                            Rating = 4.7000000000000002,
                            Resenas = 83,
                            Stock = 10,
                            TamaniosJson = "[\"S\",\"M\",\"L\"]"
                        },
                        new
                        {
                            Id = 8,
                            Badge = "Top",
                            Categoria = "Tortas Especiales",
                            Descripcion = "Irresistible red velvet con frosting de queso crema y color rojo intenso.",
                            Imagen = "https://res.cloudinary.com/ddfzttgyr/image/upload/v1774234910/Red_Velvet_da5fqq.png",
                            IngredientesJson = "[\"Cacao\",\"Colorante rojo\",\"Queso crema\",\"Harina\",\"Buttermilk\"]",
                            Nombre = "Red Velvet",
                            Precio = 90.0,
                            Rating = 4.9000000000000004,
                            Resenas = 137,
                            Stock = 8,
                            TamaniosJson = "[\"S\",\"M\",\"L\"]"
                        },
                        new
                        {
                            Id = 9,
                            Badge = "Nuevo",
                            Categoria = "Tortas",
                            Descripcion = "Esponjoso bizcocho empapado en tres tipos de leche con crema chantilly.",
                            Imagen = "https://res.cloudinary.com/ddfzttgyr/image/upload/v1774234917/Tres_Leches_d8lm11.png",
                            IngredientesJson = "[\"Leche condensada\",\"Leche evaporada\",\"Crema\",\"Huevos\",\"Harina\"]",
                            Nombre = "Tres Leches",
                            Precio = 70.0,
                            Rating = 4.7999999999999998,
                            Resenas = 91,
                            Stock = 14,
                            TamaniosJson = "[\"S\",\"M\",\"L\"]"
                        },
                        new
                        {
                            Id = 10,
                            Badge = "Nuevo",
                            Categoria = "Tortas Especiales",
                            Descripcion = "Exquisita torta con mix de frutos del bosque frescos y crema.",
                            Imagen = "https://res.cloudinary.com/ddfzttgyr/image/upload/v1774234923/Torta_de_Frutos_del_Bosque_sfpmtk.png",
                            IngredientesJson = "[\"Frutos del bosque\",\"Crema\",\"Harina\",\"Huevos\",\"Azúcar\"]",
                            Nombre = "Torta de Frutos del Bosque",
                            Precio = 95.0,
                            Rating = 4.7999999999999998,
                            Resenas = 72,
                            Stock = 6,
                            TamaniosJson = "[\"S\",\"M\",\"L\"]"
                        });
                });

            modelBuilder.Entity("TortasYaniAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
